rabbitmq_user: fix node argument parsing (#32)
ansible-collections/community.rabbitmq pull request #43
Opened 2020-08-19 15:19 UTC by Davasny

##### SUMMARY
Due to not passing `type='bool'` in `node` argument to  `AnsibleModule` it was parsed as `string` and `if` statement in line 264 always returned `true`. Fixes #32 

https://github.com/ansible-collections/community.rabbitmq/blob/981891b670476a00be6beae308f54da2c2b87ed8/plugins/modules/rabbitmq_user.py#L264-L265 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

rabbitmq_user

##### ADDITIONAL INFORMATION

Like above

```paste below

```

2020-11-06 13:51 UTC, odyssey4me requested changes
I think there's a misunderstanding here - the node argument is a string. The conditional ``if self.node`` is not checking a boolean value, it's checking if the ``node`` argument has a value.

2020-11-06 13:51 UTC, odyssey4me commented on plugins/modules/rabbitmq_user.py
> +        node=dict(default='rabbit', type='bool'),
This is not a boolean type, it is a string with the default value of 'rabbit'.

2021-07-16 06:41 UTC, Andersson007 commented
Is this PR still relevant? Can we help with anything? @Davasny please update the PR or close it.

2021-07-21 08:43 UTC, Andersson007 commented
as no response, I'll close this. @Davasny thanks anyway! If you get interested in finishing this, please comment and we'll reopen it

2021-07-21 08:43 UTC, closed without merging

2021-07-21 08:51 UTC, Davasny commented
Sorry, I forgot to answear here. There was a bug in PR and I'll try to fix it in the future, for now let's keep it closed

2021-07-21 09:18 UTC, Andersson007 commented
@Davasny thanks for the feedback! Once you decide to continue, please let us know