WIP: Update the integration setup playbook
ansible-collections/community.rabbitmq pull request #75
Opened 2021-06-02 10:07 UTC by abompard

The [installation instructions](https://www.rabbitmq.com/install-debian.html) have changed, these updates allow the integration container to build and run the tests.

2021-07-14 16:46 UTC, cognifloyd commented
azure pipelines says that logs are kept for 3 days, so I'm going to copy the relevant parts of the error output in here so I don't lose them. Sorry for the really long message.

It looks like the errors are ubuntu-specific. 16 has an issue with the signing key and 18 has an issue resolving which packages to install.

#### CI (Docker 2.9 Ubuntu 16.04) -> 
```
01:11 TASK [setup_rabbitmq : Team RabbitMQ's main signing key] ***********************
01:12 fatal: [testhost]: FAILED! => {
01:12     "cmd": "/usr/bin/apt-key adv --no-tty --keyserver hkps://keys.openpgp.org --recv 0A9AF2115F4687BD29803A206B73A36E6026DFCA", 
01:12     "msg": "Error fetching key 0A9AF2115F4687BD29803A206B73A36E6026DFCA from keyserver: hkps://keys.openpgp.org", 
01:12     "rc": 2, 
01:12     "stderr_lines": [
01:12         "gpg: requesting key 6026DFCA from hkps server keys.openpgp.org", 
01:12         "gpg: no valid OpenPGP data found.", 
01:12         "gpg: Total number processed: 0", 
01:12         "gpg: keyserver communications error: ?", 
01:12         "gpg: keyserver communications error: g10err=127", 
01:12         "gpg: keyserver receive failed: g10err=127"
01:12     ], 
01:12     "stdout_lines": [
01:12         "Executing: /tmp/tmp.ccuzbUZxK6/gpg.1.sh --no-tty", 
01:12         "--keyserver", 
01:12         "hkps://keys.openpgp.org", 
01:12         "--recv", 
01:12         "0A9AF2115F4687BD29803A206B73A36E6026DFCA", 
01:12         "gpgkeys: HTTP fetch error 1: unsupported protocol"
01:12     ]
```
#### CI (Docker 2.10 Ubuntu 16.04) -> 
```
01:08 TASK [setup_rabbitmq : Team RabbitMQ's main signing key] ***********************
01:09 fatal: [testhost]: FAILED! => {
01:09     "cmd": "/usr/bin/apt-key adv --no-tty --keyserver hkps://keys.openpgp.org --recv 0A9AF2115F4687BD29803A206B73A36E6026DFCA", 
01:09     "msg": "Error fetching key 0A9AF2115F4687BD29803A206B73A36E6026DFCA from keyserver: hkps://keys.openpgp.org", 
01:09     "rc": 2, 
01:09     "stderr_lines": [
01:09         "gpg: requesting key 6026DFCA from hkps server keys.openpgp.org", 
01:09         "gpg: no valid OpenPGP data found.", 
01:09         "gpg: Total number processed: 0", 
01:09         "gpg: keyserver communications error: ?", 
01:09         "gpg: keyserver communications error: g10err=127", 
01:09         "gpg: keyserver receive failed: g10err=127"
01:09     ], 
01:09     "stdout_lines": [
01:09         "Executing: /tmp/tmp.KR1vOvdqGl/gpg.1.sh --no-tty", 
01:09         "--keyserver", 
01:09         "hkps://keys.openpgp.org", 
01:09         "--recv", 
01:09         "0A9AF2115F4687BD29803A206B73A36E6026DFCA", 
01:09         "gpgkeys: HTTP fetch error 1: unsupported protocol"
01:09     ]
```
#### CI (Docker 2.9 Ubuntu 18.04) -> 
```
01:41 TASK [setup_rabbitmq : Install Erlang packages] ********************************
01:42 fatal: [testhost]: FAILED! => {
01:42     "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'erlang-base' 'erlang-asn1' 'erlang-crypto' 'erlang-eldap' 'erlang-ftp' 'erlang-inets' 'erlang-mnesia' 'erlang-os-mon' 'erlang-parsetools' 'erlang-public-key' 'erlang-runtime-tools' 'erlang-snmp' 'erlang-ssl' 'erlang-syntax-tools' 'erlang-tftp' 'erlang-tools' 'erlang-xmerl'' failed: E: Unable to correct problems, you have held broken packages.\n",
01:42     "rc": 100,
01:42     "stderr_lines": [
01:42         "E: Unable to correct problems, you have held broken packages."
01:42     ],
01:42     "stdout_lines": [
01:42         "Reading package lists...",
01:42         "Building dependency tree...",
01:42         "Reading state information...",
01:42         "Some packages could not be installed. This may mean that you have",
01:42         "requested an impossible situation or if you are using the unstable",
01:42         "distribution that some required packages have not yet been created",
01:42         "or been moved out of Incoming.",
01:42         "The following information may help to resolve the situation:",
01:42         "",
01:42         "The following packages have unmet dependencies:",
01:42         " erlang-ftp : Depends: erlang-base (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or",
01:42         "                       erlang-base-hipe (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but it is not going to be installed",
01:42         "              Depends: erlang-runtime-tools (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed",
01:42         "              Depends: erlang-ssl (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed",
01:42         " erlang-tftp : Depends: erlang-base (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or",
01:42         "                        erlang-base-hipe (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but it is not going to be installed"
01:42     ]
```
#### CI (Docker 2.10 Ubuntu 18.04) -> 
```
01:30 TASK [setup_rabbitmq : Install Erlang packages] ********************************
01:31 fatal: [testhost]: FAILED! => {
01:31     "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'erlang-base' 'erlang-asn1' 'erlang-crypto' 'erlang-eldap' 'erlang-ftp' 'erlang-inets' 'erlang-mnesia' 'erlang-os-mon' 'erlang-parsetools' 'erlang-public-key' 'erlang-runtime-tools' 'erlang-snmp' 'erlang-ssl' 'erlang-syntax-tools' 'erlang-tftp' 'erlang-tools' 'erlang-xmerl'' failed: E: Unable to correct problems, you have held broken packages.\n",
01:31     "rc": 100,
01:31     "stderr_lines": [
01:31         "E: Unable to correct problems, you have held broken packages."
01:31     ],
01:31     "stdout_lines": [
01:31         "Reading package lists...",
01:31         "Building dependency tree...",
01:31         "Reading state information...",
01:31         "Some packages could not be installed. This may mean that you have",
01:31         "requested an impossible situation or if you are using the unstable",
01:31         "distribution that some required packages have not yet been created",
01:31         "or been moved out of Incoming.",
01:31         "The following information may help to resolve the situation:",
01:31         "",
01:31         "The following packages have unmet dependencies:",
01:31         " erlang-ftp : Depends: erlang-base (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or",
01:31         "                       erlang-base-hipe (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but it is not going to be installed",
01:31         "              Depends: erlang-runtime-tools (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed",
01:31         "              Depends: erlang-ssl (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed",
01:31         " erlang-tftp : Depends: erlang-base (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but 1:20.2.2+dfsg-1ubuntu2 is to be installed or",
01:31         "                        erlang-base-hipe (= 1:22.0.7+dfsg-1build1~ubuntu18.04.1) but it is not going to be installed"
01:31     ]
```
#### CI (Docker 2.11 Ubuntu 18.04) -> 
```
01:43 TASK [setup_rabbitmq : Install Erlang packages] ********************************
01:44 fatal: [testhost]: FAILED! => {
01:44     "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'erlang-base' 'erlang-asn1' 'erlang-crypto' 'erlang-eldap' 'erlang-ftp' 'erlang-inets' 'erlang-mnesia' 'erlang-os-mon' 'erlang-parsetools' 'erlang-public-key' 'erlang-runtime-tools' 'erlang-snmp' 'erlang-ssl' 'erlang-syntax-tools' 'erlang-tftp' 'erlang-tools' 'erlang-xmerl'' failed: E: Unable to correct problems, you have held broken packages.\n",
01:44     "rc": 100,
01:44     "stderr_lines": [
01:44         "E: Unable to correct problems, you have held broken packages."
01:44     ],
01:44     "std [...]

2021-07-14 16:50 UTC, cognifloyd commented
@abompard Are these the same errors you saw last time? It sounds like they are different. In https://github.com/ansible-collections/community.rabbitmq/issues/72#issuecomment-852900365 you said:
> I'm stuck with systemctl failing in the ubuntu container that ansible-test creates.

2021-07-14 17:04 UTC, cognifloyd commented
Ubuntu 16 is EOL (since April 30th), so maybe we should:
- drop Ubuntu 16 from the test matrix
- get Ubuntu 18 working
- add Ubuntu 20 (in #44)

2021-07-14 17:15 UTC, cognifloyd commented
Also, RabbitMQ only supports: "Ubuntu 18.04 through 21.04" so we really should drop ubuntu 16.
https://www.rabbitmq.com/install-debian.html#supported-distributions

2021-07-15 03:21 UTC, cognifloyd requested changes
I'm hoping that these 3 changes will fix the ubuntu 18 stages. wdyt?

2021-07-15 03:21 UTC, cognifloyd commented on tests/integration/targets/setup_rabbitmq/tasks/ubuntu.yml
> +    update_cache: no
why did you disable update_cache? This might be (part of) why it's getting so many package conflicts.
```suggestion
    update_cache: yes
```

2021-07-15 03:21 UTC, cognifloyd commented on tests/integration/targets/setup_rabbitmq/tasks/ubuntu.yml
> +    update_cache: no
```suggestion
    update_cache: yes
```

2021-07-15 03:21 UTC, cognifloyd commented on tests/integration/targets/setup_rabbitmq/tasks/ubuntu.yml
> +    name: rabbitmq-server
The docs say to use `--fix-missing` when installing `rabbitmq-server, so I believe we need to use `state:fixed` here.
```suggestion
    name: rabbitmq-server
    state: fixed
```

2021-07-16 06:26 UTC, Andersson007 commented
@cognifloyd hi, would you like to create a PR to update the playbook yourself? I'd be happy to review and merge it

2021-07-16 06:53 UTC, Andersson007 commented
@abompard do you have time / with to finish it?
A guy who will fix the CI will be like a savior of the collection.

2021-07-16 07:01 UTC, abompard commented
I may have some time but I'm also unfamiliar with the ansible testing framework and the Azure pipelines. So if someone else wants to take over I'll gladly pass it on :-) I just want CI to work so I can contribute some feature to the rabbitmq modules.

2021-07-16 08:36 UTC, Andersson007 commented
@abompard thanks for the feedback! How about the changes that @cognifloyd suggested?

2021-07-16 10:04 UTC, abompard commented
I appied them and force pushed

2021-07-16 13:00 UTC, Andersson007 commented
https://github.com/ansible-collections/community.rabbitmq/pull/78
https://github.com/ansible-collections/community.rabbitmq/issues/79

2021-07-16 13:03 UTC, Andersson007 commented
@abompard i think this PR can be closed since i made a temporary (hehe) solution https://github.com/ansible-collections/community.rabbitmq/pull/78. Thank you for the attempt!

If anyone is interested in improving the CI, welcome https://github.com/ansible-collections/community.rabbitmq/issues/79

@abompard @cognifloyd thanks!

2021-07-16 16:39 UTC, cognifloyd commented
I just saw all your messages.

> i think this PR can be closed since i made a temporary (hehe) solution #78. Thank you for the attempt!

@Andersson007 LOL - disabling all the envs is quite the hack.

 Sure, I can create another PR to fix this stuff.

2021-07-16 16:46 UTC, cognifloyd commented
Just looked at the test results. How encouraging :) so, my suggested fixes fixed Ubuntu 18 + ansible 2.10, 2.11, and devel. The fixes did not make Ubuntu 18 + ansible 2.9 work, however. Also, Ubuntu 20 didn't work.

I figure we can enable one set of distros in each PR until we get them all working.

2021-07-19 08:37 UTC, Andersson007 commented
@cognifloyd 

> @Andersson007 LOL - disabling all the envs is quite the hack.

Yes, it is:) Though the tests were actually running only on Ubuntu. And the errors on Ubuntu 16 / 18 didn't seem to relate to the modules themselves.

> Sure, I can create another PR to fix this stuff.

Would be really cool! Ping me there for review.

> I figure we can enable one set of distros in each PR until we get them all working.

Acting gradually sounds sensible to me.

I'll close this PR then. @abompard would be nice if you take part in the future PRs dedicated to fixing the CI. It is really important for stability of this stuff. The many eyes / opinios, the better. Thank you!

2021-07-19 08:37 UTC, closed without merging